name: jotagefirstplugin
version: '${project.version}'
main: com.joaoguedes.jotagefirstplugin.Jotagefirstplugin
api-version: '1.17'
commands:
  fp:
    description: "Liga ou Desliga o plugin!"
    usage: "§c/fp <ligar | desligar | reload>"
