name: jotagefirstplugin
version: '${project.version}'
main: com.joaoguedes.jotagefirstplugin.Jotagefirstplugin
api-version: '1.17'
commands:
  firstplugintoggle:
    description: Liga ou desliga o plugin.
    usage: /firstplugintoggle
