name: jotagefirstplugin
version: '1.0'
main: com.joaoguedes.jotagefirstplugin.Jotagefirstplugin
api-version: '1.17'
commands:
  fp:
    description: "Liga ou Desliga o plugin!"
    usage: "/fp <ligar|desligar|reload>"
